'use client'

import { motion } from 'framer-motion'
import { LayoutGrid, Clock, Layers, Link2, Gauge, UserCircle2 } from 'lucide-react'
import { useProjectStore } from '@/lib/project-store'
import { useEffect, useState } from 'react'
import { getUsers, updateBacklog } from '@/lib/api'
import { useAppUser } from '@/lib/auth-context'

const priorityPill: Record<string, string> = {
  critical: 'bg-rose-50 text-rose-700 border-rose-200',
  high: 'bg-red-50 text-red-700 border-red-200',
  medium: 'bg-amber-50 text-amber-700 border-amber-200',
  low: 'bg-emerald-50 text-emerald-700 border-emerald-200',
}

const loadBarColor: Record<string, string> = {
  high: 'bg-rose-500',
  medium: 'bg-amber-500',
  low: 'bg-emerald-500',
}

const KANBAN_COLUMNS = ['To Do', 'In Progress', 'In Review', 'Done']

export function SprintBoardView() {
  const project = useProjectStore((s) => s.project)
  const setProject = useProjectStore((s) => s.setProject)
  const backlog = project?.backlog || null
  const { user: currentUser } = useAppUser()

  const [viewMode, setViewMode] = useState<'sprint' | 'kanban'>('kanban')
  const [users, setUsers] = useState<any[]>([])
  
  useEffect(() => {
    getUsers().then(res => setUsers(res.users || [])).catch(console.error)
  }, [])

  if (!backlog) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 tracking-tight mb-1">Sprint Board</h2>
          <p className="text-slate-500 text-sm">Interactive agile board of every sprint and task</p>
        </div>
        <div className="bg-white border border-slate-200 p-12 rounded-2xl shadow-xs flex flex-col items-center justify-center text-center">
          <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center mb-3">
            <LayoutGrid className="w-6 h-6" />
          </div>
          <p className="text-sm font-semibold text-slate-900">Sprint board is being generated by the AI organization.</p>
          <p className="text-xs text-slate-500 mt-1 max-w-sm">
            The sprint planner is balancing capacity and distributing tasks.
          </p>
        </div>
      </div>
    )
  }

  const tasks = backlog.tasks || []
  const sprints = [...(backlog.sprints || [])].sort((a, b) => a.number - b.number)

  // Ensure tasks have statuses
  const normalizedTasks = tasks.map((t: any) => ({ ...t, status: t.status || 'To Do' }))

  const updateTask = async (taskTitle: string, updates: Partial<any>) => {
    if (!project) return
    const newTasks = normalizedTasks.map((t: any) => t.title === taskTitle ? { ...t, ...updates } : t)
    const newBacklog = { ...backlog, tasks: newTasks }
    
    // Optimistic UI update
    setProject({ ...project, backlog: newBacklog })
    
    try {
      await updateBacklog(project.id, newBacklog)
    } catch (err) {
      console.error("Failed to update task", err)
      // Rollback
      setProject({ ...project, backlog })
    }
  }

  const handleDrop = (e: React.DragEvent, status: string) => {
    e.preventDefault()
    const taskTitle = e.dataTransfer.getData('text/plain')
    if (taskTitle) {
      updateTask(taskTitle, { status })
    }
  }

  const renderTaskCard = (task: any, idx: number) => {
    const deps = task.dependencies?.length || 0
    return (
      <div
        key={`${task.title}-${idx}`}
        draggable
        onDragStart={(e: any) => e.dataTransfer.setData('text/plain', task.title)}
        className="p-3.5 bg-white border border-slate-200 rounded-xl hover:border-slate-300 hover:shadow-sm transition-all cursor-grab active:cursor-grabbing shadow-xs"
      >
        <div className="flex items-start justify-between gap-2">
          <p className="font-semibold text-xs text-slate-900 leading-snug">{task.title}</p>
          <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border flex-shrink-0 capitalize ${priorityPill[task.priority] || priorityPill.medium}`}>
            {task.priority || 'medium'}
          </span>
        </div>

        <div className="flex items-center gap-2 mt-2 flex-wrap">
          {task.category && (
            <span className="text-[10px] font-medium uppercase tracking-wider text-slate-600 bg-slate-100 border border-slate-200 px-2 py-0.5 rounded">
              {task.category}
            </span>
          )}
          <span className="flex items-center gap-1 text-[10px] text-slate-500 bg-slate-50 border border-slate-200 px-2 py-0.5 rounded">
            <Clock className="w-3 h-3 text-slate-400" /> {task.estimated_days}d
          </span>
          {deps > 0 && (
            <span className="flex items-center gap-1 text-[10px] text-blue-700 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded">
              <Link2 className="w-3 h-3 text-blue-500" /> {deps} {deps === 1 ? 'dep' : 'deps'}
            </span>
          )}
        </div>

        <div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-2 text-[11px]">
          <div className="relative">
            <select 
              className="bg-slate-50 border border-slate-200 rounded text-[11px] text-slate-600 hover:text-slate-900 cursor-pointer outline-none px-2 py-0.5 max-w-[130px] truncate"
              value={task.assignee_id || ''}
              onChange={(e) => updateTask(task.title, { assignee_id: e.target.value })}
              disabled={currentUser?.role === 'developer' && task.assignee_id && task.assignee_id !== currentUser.id}
            >
              <option value="">Unassigned</option>
              {users.map(u => (
                <option key={u.id} value={u.id}>{u.first_name} {u.last_name}</option>
              ))}
            </select>
          </div>
          {task.epic && (
            <p className="text-[10px] text-slate-500 flex items-center gap-1 max-w-[110px] truncate" title={task.epic}>
              <Layers className="w-3 h-3 flex-shrink-0 text-slate-400" /> {task.epic}
            </p>
          )}
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 tracking-tight mb-0.5">Sprint Board</h2>
          <p className="text-slate-500 text-sm">
            {sprints.length} sprints · drag and drop tasks to update delivery status
          </p>
        </div>
        <div className="flex bg-slate-100 border border-slate-200 rounded-lg p-1">
          <button 
            className={`px-3 py-1 text-xs font-semibold rounded-md transition-colors ${viewMode === 'kanban' ? 'bg-white text-slate-900 shadow-xs' : 'text-slate-600 hover:text-slate-900'}`}
            onClick={() => setViewMode('kanban')}
          >
            Kanban Board
          </button>
          <button 
            className={`px-3 py-1 text-xs font-semibold rounded-md transition-colors ${viewMode === 'sprint' ? 'bg-white text-slate-900 shadow-xs' : 'text-slate-600 hover:text-slate-900'}`}
            onClick={() => setViewMode('sprint')}
          >
            Sprint Columns
          </button>
        </div>
      </div>

      {viewMode === 'kanban' ? (
        <div className="flex gap-4 overflow-x-auto pb-4 items-start min-h-[500px]">
          {KANBAN_COLUMNS.map((colName) => {
            const colTasks = normalizedTasks.filter((t: any) => t.status === colName)
            return (
              <div
                key={colName}
                className="bg-slate-100/70 border border-slate-200 p-4 rounded-2xl flex-shrink-0 w-[290px] flex flex-col h-full min-h-[420px]"
                onDragOver={(e) => e.preventDefault()}
                onDrop={(e) => handleDrop(e, colName)}
              >
                <div className="mb-3 flex items-center justify-between">
                  <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">{colName}</h3>
                  <span className="text-xs font-semibold text-slate-500 bg-white border border-slate-200 px-2 py-0.5 rounded-full">
                    {colTasks.length}
                  </span>
                </div>
                <div className="space-y-3 flex-1">
                  {colTasks.map((task: any, idx: number) => renderTaskCard(task, idx))}
                  {colTasks.length === 0 && (
                    <div className="border border-dashed border-slate-300 rounded-xl p-4 text-center text-xs text-slate-400">
                      Drop tasks here
                    </div>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      ) : (
        <div className="flex gap-4 overflow-x-auto pb-4 items-start">
          {sprints.map((sprint) => {
            const colTasks = normalizedTasks.filter((t: any) => t.sprint === sprint.number)
            const colDays = colTasks.reduce((sum: number, t: any) => sum + (t.estimated_days || 0), 0)
            const maxSprintDays = Math.max(1, ...sprints.map(s => normalizedTasks.filter((t:any) => t.sprint === s.number).reduce((sum:number, t:any) => sum + (t.estimated_days || 0), 0)))
            const loadRatio = Math.min(1, colDays / maxSprintDays)
            const loadKey = loadRatio > 0.75 ? 'high' : loadRatio > 0.4 ? 'medium' : 'low'

            return (
              <div key={sprint.number} className="bg-slate-100/70 border border-slate-200 p-4 rounded-2xl flex-shrink-0 w-[290px] flex flex-col">
                <div className="mb-3">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-bold text-blue-600 uppercase tracking-wider">Sprint {sprint.number}</span>
                    <span className="text-[10px] font-semibold text-slate-500 bg-white border border-slate-200 px-2 py-0.5 rounded-full">
                      {colTasks.length} tasks
                    </span>
                  </div>
                  <h3 className="text-sm font-semibold text-slate-900 mt-1 leading-snug">{sprint.name}</h3>
                  <div className="mt-2.5">
                    <div className="flex items-center justify-between text-[10px] text-slate-500 mb-1 font-medium">
                      <span className="flex items-center gap-1">
                        <Gauge className="w-3 h-3 text-slate-400" /> Sprint Load
                      </span>
                      <span className="font-semibold text-slate-900">{Math.round(colDays)}d</span>
                    </div>
                    <div className="h-1.5 bg-slate-200 rounded-full overflow-hidden">
                      <div className={`h-full ${loadBarColor[loadKey]}`} style={{ width: `${Math.max(4, loadRatio * 100)}%` }} />
                    </div>
                  </div>
                </div>
                <div className="space-y-3 flex-1">
                  {colTasks.map((task: any, idx: number) => renderTaskCard(task, idx))}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
