'use client'

import { motion } from 'framer-motion'
import { LayoutGrid, Clock, Layers, Link2, Target, ListChecks, Gauge, ChevronDown, UserCircle2 } from 'lucide-react'
import { useProjectStore } from '@/lib/project-store'
import { useEffect, useState } from 'react'
import { getUsers, updateBacklog } from '@/lib/api'
import { useAppUser } from '@/lib/auth-context'

const priorityPill: Record<string, string> = {
  critical: 'bg-rose-500/20 text-rose-400 border border-rose-500/30',
  high: 'bg-red-500/20 text-red-400 border border-red-500/30',
  medium: 'bg-amber-500/20 text-amber-400 border border-amber-500/30',
  low: 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30',
}

const loadBarColor: Record<string, string> = {
  high: 'from-rose-500 to-red-500',
  medium: 'from-amber-400 to-amber-500',
  low: 'from-cyan-400 to-emerald-400',
}

const KANBAN_COLUMNS = ['To Do', 'In Progress', 'In Review', 'Done']

export function SprintBoardView() {
  const project = useProjectStore((s) => s.project)
  const setProject = useProjectStore((s) => s.setProject)
  const backlog = project?.backlog || null
  const { user: currentUser } = useAppUser()

  const [viewMode, setViewMode] = useState<'sprint' | 'kanban'>('kanban')
  const [users, setUsers] = useState<any[]>([])
  
  useEffect(() => {
    getUsers().then(res => setUsers(res.users || [])).catch(console.error)
  }, [])

  if (!backlog) {
    return (
      <motion.div className="space-y-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
        <div>
          <h2 className="text-3xl font-bold text-foreground mb-2">Sprint Board</h2>
          <p className="text-muted-foreground">A live agile board of every sprint and its tasks</p>
        </div>
        <div className="glass-panel p-12 rounded-xl flex flex-col items-center justify-center text-center">
          <motion.div
            className="w-16 h-16 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center mb-5"
            animate={{ opacity: [0.4, 1, 0.4], scale: [0.96, 1, 0.96] }}
            transition={{ duration: 1.8, repeat: Infinity, ease: 'easeInOut' }}
          >
            <LayoutGrid className="w-8 h-8 text-primary" />
          </motion.div>
          <p className="text-lg font-semibold text-foreground">Sprint board is being generated by the AI organization.</p>
          <p className="text-sm text-muted-foreground mt-2 max-w-md">
            The planning agents are slicing the backlog into sprints and balancing capacity. Hang tight.
          </p>
        </div>
      </motion.div>
    )
  }

  const tasks = backlog.tasks || []
  const sprints = [...(backlog.sprints || [])].sort((a, b) => a.number - b.number)
  const totalDays = tasks.reduce((sum: number, t: any) => sum + (t.estimated_days || 0), 0)

  // Ensure tasks have statuses
  const normalizedTasks = tasks.map((t: any) => ({ ...t, status: t.status || 'To Do' }))

  const updateTask = async (taskTitle: string, updates: Partial<any>) => {
    if (!project) return
    const newTasks = normalizedTasks.map((t: any) => t.title === taskTitle ? { ...t, ...updates } : t)
    const newBacklog = { ...backlog, tasks: newTasks }
    
    // Optimistic UI update
    setProject({ ...project, backlog: newBacklog })
    
    try {
      await updateBacklog(project.id, newBacklog)
    } catch (err) {
      console.error("Failed to update task", err)
      // Rollback
      setProject({ ...project, backlog })
    }
  }

  const handleDrop = (e: React.DragEvent, status: string) => {
    e.preventDefault()
    const taskTitle = e.dataTransfer.getData('text/plain')
    if (taskTitle) {
      updateTask(taskTitle, { status })
    }
  }

  const renderTaskCard = (task: any, idx: number) => {
    const deps = task.dependencies?.length || 0
    return (
      <motion.div
        key={`${task.title}-${idx}`}
        draggable
        onDragStart={(e: any) => e.dataTransfer.setData('text/plain', task.title)}
        className="p-3 bg-card/60 border border-white/10 rounded-lg hover:border-primary/50 hover:bg-card/80 transition-colors cursor-grab active:cursor-grabbing"
        whileHover={{ y: -3 }}
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="flex items-start justify-between gap-2">
          <p className="font-medium text-sm text-foreground leading-snug">{task.title}</p>
          <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full flex-shrink-0 capitalize ${priorityPill[task.priority] || priorityPill.medium}`}>
            {task.priority || 'medium'}
          </span>
        </div>

        <div className="flex items-center gap-2 mt-2 flex-wrap">
          {task.category && (
            <span className="text-[10px] uppercase tracking-wide text-secondary bg-[#7c3aed]/15 border border-[#7c3aed]/25 px-2 py-0.5 rounded">
              {task.category}
            </span>
          )}
          <span className="flex items-center gap-1 text-[10px] text-muted-foreground bg-white/5 px-2 py-0.5 rounded">
            <Clock className="w-3 h-3" /> {task.estimated_days}d
          </span>
          {deps > 0 && (
            <span className="flex items-center gap-1 text-[10px] text-cyan-400/80 bg-cyan-500/10 px-2 py-0.5 rounded">
              <Link2 className="w-3 h-3" /> {deps} {deps === 1 ? 'dep' : 'deps'}
            </span>
          )}
        </div>

        <div className="mt-3 flex items-center justify-between border-t border-white/5 pt-2">
           <div className="relative group">
              <select 
                className="appearance-none bg-transparent text-[11px] text-muted-foreground hover:text-foreground cursor-pointer outline-none w-32 truncate"
                value={task.assignee_id || ''}
                onChange={(e) => updateTask(task.title, { assignee_id: e.target.value })}
                disabled={currentUser?.role === 'developer' && task.assignee_id && task.assignee_id !== currentUser.id}
              >
                <option value="">Unassigned</option>
                {users.map(u => (
                  <option key={u.id} value={u.id}>{u.first_name} {u.last_name}</option>
                ))}
              </select>
           </div>
           {task.epic && (
            <p className="text-[10px] text-muted-foreground flex items-center gap-1 max-w-[100px] truncate" title={task.epic}>
              <Layers className="w-3 h-3 flex-shrink-0" /> {task.epic}
            </p>
          )}
        </div>
      </motion.div>
    )
  }

  return (
    <motion.div className="space-y-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-foreground mb-2">Sprint Board</h2>
          <p className="text-muted-foreground">
            A live agile board — {sprints.length} sprints · drag and drop tasks to update progress
          </p>
        </div>
        <div className="flex bg-card border border-white/10 rounded-lg p-1">
          <button 
            className={`px-4 py-1.5 text-sm font-medium rounded-md transition-colors ${viewMode === 'kanban' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`}
            onClick={() => setViewMode('kanban')}
          >
            Kanban
          </button>
          <button 
            className={`px-4 py-1.5 text-sm font-medium rounded-md transition-colors ${viewMode === 'sprint' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`}
            onClick={() => setViewMode('sprint')}
          >
            Sprint Timeline
          </button>
        </div>
      </div>

      {viewMode === 'kanban' ? (
        <div className="flex gap-4 overflow-x-auto pb-4 items-start min-h-[500px]">
          {KANBAN_COLUMNS.map((colName) => {
            const colTasks = normalizedTasks.filter((t: any) => t.status === colName)
            return (
              <div
                key={colName}
                className="glass-panel-dark p-4 rounded-xl flex-shrink-0 w-[300px] flex flex-col h-full min-h-[400px]"
                onDragOver={(e) => e.preventDefault()}
                onDrop={(e) => handleDrop(e, colName)}
              >
                <div className="mb-4 flex items-center justify-between">
                  <h3 className="text-sm font-semibold text-foreground uppercase tracking-wider">{colName}</h3>
                  <span className="text-xs font-mono text-muted-foreground bg-white/5 px-2 py-0.5 rounded-full">
                    {colTasks.length}
                  </span>
                </div>
                <div className="space-y-3 flex-1">
                  {colTasks.map((task: any, idx: number) => renderTaskCard(task, idx))}
                  {colTasks.length === 0 && (
                    <div className="border border-dashed border-white/10 rounded-lg p-4 text-center text-xs text-muted-foreground opacity-50">
                      Drop tasks here
                    </div>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      ) : (
        <div className="flex gap-4 overflow-x-auto pb-4 items-start">
          {sprints.map((sprint, sIdx) => {
            const colTasks = normalizedTasks.filter((t: any) => t.sprint === sprint.number)
            const colDays = colTasks.reduce((sum: number, t: any) => sum + (t.estimated_days || 0), 0)
            const maxSprintDays = Math.max(1, ...sprints.map(s => normalizedTasks.filter((t:any) => t.sprint === s.number).reduce((sum:number, t:any) => sum + (t.estimated_days || 0), 0)))
            const loadRatio = Math.min(1, colDays / maxSprintDays)
            const loadKey = loadRatio > 0.75 ? 'high' : loadRatio > 0.4 ? 'medium' : 'low'

            return (
              <div key={sprint.number} className="glass-panel-dark p-4 rounded-xl flex-shrink-0 w-[280px] flex flex-col">
                <div className="mb-4">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-semibold text-primary uppercase tracking-wider">Sprint {sprint.number}</span>
                    <span className="text-[10px] text-muted-foreground bg-white/5 px-2 py-0.5 rounded-full">
                      {colTasks.length} tasks
                    </span>
                  </div>
                  <h3 className="text-base font-semibold text-foreground mt-1 leading-snug">{sprint.name}</h3>
                  <div className="mt-3">
                    <div className="flex items-center justify-between text-[10px] text-muted-foreground mb-1">
                      <span className="flex items-center gap-1">
                        <Gauge className="w-3 h-3" /> Load
                      </span>
                      <span className="font-semibold text-foreground/80">{Math.round(colDays)}d</span>
                    </div>
                    <div className="h-1.5 bg-card rounded-full overflow-hidden">
                      <div className={`h-full bg-gradient-to-r ${loadBarColor[loadKey]}`} style={{ width: `${Math.max(4, loadRatio * 100)}%` }} />
                    </div>
                  </div>
                </div>
                <div className="space-y-3 flex-1">
                  {colTasks.map((task: any, idx: number) => renderTaskCard(task, idx))}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </motion.div>
  )
}
