'use client'
import {useState} from 'react'
import {useRouter,useSearchParams} from 'next/navigation'
import {ArrowRight,Loader2,Users,Clock,DollarSign,FileText} from 'lucide-react'
import {analyzeProject} from '@/lib/api'
import {useAppStore} from '@/lib/store'
import {WorkspaceAuthGate} from '@/components/auth/workspace-auth-gate'

const control='w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
export default function NewProjectPage(){return <WorkspaceAuthGate><ProjectIntake/></WorkspaceAuthGate>}
function ProjectIntake(){
 const router=useRouter(),params=useSearchParams(),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({title:'',idea:params.get('idea')||'',team_size:4,timeline_weeks:12,budget_usd:50000,methodology:'Agile',team_skills:'Frontend, Backend, Product',priorities:'MVP, Security, Reliability',constraints:'',reference_title:'Product brief / source of truth',reference_content:''})
 const set=(key:string,value:any)=>setForm(v=>({...v,[key]:value}))
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const result=await analyzeProject(form.idea,form.title||undefined,{team_size:Number(form.team_size),timeline_weeks:Number(form.timeline_weeks)||null,budget_usd:Number(form.budget_usd)||null,methodology:form.methodology,team_skills:form.team_skills.split(',').map(x=>x.trim()).filter(Boolean),priorities:form.priorities.split(',').map(x=>x.trim()).filter(Boolean),constraints:form.constraints,source_documents:form.reference_content.trim()?[{title:form.reference_title.trim()||'Project reference',content:form.reference_content.trim(),source_type:'spec',mime_type:'text/plain',metadata:{authoritative:true}}]:[]});useAppStore.getState().setActiveWorkspaceMode('track-live');router.push(`/workspace?project=${result.project_id}`)}catch(err:any){setError(err.message||'Failed to create project');setBusy(false)}}
 return <main className="min-h-screen bg-slate-50 px-4 py-12"><form onSubmit={submit} className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Manager intake</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Plan a new project</h1><p className="mt-2 text-sm text-slate-500">Give the AI organization real delivery constraints. You can edit all of these later.</p></div>
 <div className="grid gap-5 sm:grid-cols-2"><Field label="Project name"><input required value={form.title} onChange={e=>set('title',e.target.value)} className={control} placeholder="Customer Portal"/></Field><Field label="Methodology"><select value={form.methodology} onChange={e=>set('methodology',e.target.value)} className={control}><option>Agile</option><option>Scrum</option><option>Kanban</option><option>Waterfall</option><option>Hybrid</option></select></Field><Field wide label="What are you building?"><textarea required minLength={8} rows={5} value={form.idea} onChange={e=>set('idea',e.target.value)} className={control} placeholder="Describe users, problem, and desired outcome"/></Field><Field label="People available" icon={Users}><input type="number" min="1" max="200" value={form.team_size} onChange={e=>set('team_size',e.target.value)} className={control}/></Field><Field label="Target timeline (weeks)" icon={Clock}><input type="number" min="1" max="260" value={form.timeline_weeks} onChange={e=>set('timeline_weeks',e.target.value)} className={control}/></Field><Field label="Budget (USD)" icon={DollarSign}><input type="number" min="0" value={form.budget_usd} onChange={e=>set('budget_usd',e.target.value)} className={control}/></Field><Field label="Available skills"><input value={form.team_skills} onChange={e=>set('team_skills',e.target.value)} className={control} placeholder="React, Python, QA"/></Field><Field wide label="Manager priorities"><input value={form.priorities} onChange={e=>set('priorities',e.target.value)} className={control} placeholder="MVP, compliance, performance"/></Field><Field wide label="Constraints, dependencies, or non-negotiables"><textarea rows={3} value={form.constraints} onChange={e=>set('constraints',e.target.value)} className={control} placeholder="Launch date, existing stack, compliance, integrations…"/></Field><Field wide label="Reference title (optional)" icon={FileText}><input value={form.reference_title} onChange={e=>set('reference_title',e.target.value)} className={control} placeholder="Approved PRD, technical spec, or customer research"/></Field><Field wide label="Authoritative reference context for RAG (optional)" icon={FileText}><textarea rows={7} value={form.reference_content} onChange={e=>set('reference_content',e.target.value)} className={control} placeholder="Paste a PRD, requirements, existing architecture notes, ticket export, or other source of truth. Agents retrieve and cite the most relevant chunks for their dedicated work."/><span className="mt-1.5 block text-xs leading-5 text-slate-500">This source is stored inside the project workspace, chunked, and indexed with tenant-scoped hybrid retrieval before agents run.</span></Field></div>
 {error&&<p role="alert" className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-7 flex justify-end"><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ArrowRight className="h-4 w-4"/>}{busy?'Starting AI organization…':'Create and orchestrate'}</button></div></form></main>
}
function Field({label,wide=false,icon:Icon,children}:{label:string,wide?:boolean,icon?:any,children:React.ReactNode}){return <label className={wide?'sm:col-span-2':''}><span className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-slate-700">{Icon&&<Icon className="h-3.5 w-3.5 text-blue-600"/>}{label}</span>{children}</label>}
